### ISSUE TITLE
Contact email address for translated websites

### ISSUE THREAD

**Issue by benthamite** [whyboris/utilitarianism.net#137]
The “[about us](https://utilitarismo.net/sobre-nosotros/)” page of the Spanish website lists `contact[at]utilitarismo.net` as the contact email address. I’m not sure if this is deliberate, but I think it should be either `contacto[at]utilitarismo.net` or `contact[at]utilitarianism.net`. I would tentatively recommend the latter, which would avoid the need to check and maintain multiple email addresses.

I haven’t looked into the German website, but I assume it has the same issue.

**Comment by whyboris** [comment]
Thank you @benthamite for catching this! Looks like it only affected the Spanish version of the website.
Fixed with https://github.com/whyboris/utilitarianism.net/commit/9b0f8a72c83f8982d4162d29bda227617b284099 🤝 
All websites point to the same active email address 👍
